### ISSUE TITLE
Copy button didn't work

### ISSUE THREAD

**Issue by xcloudx87** [Jaydee94/kubeseal-webgui#122]
**Describe the bug**
After sealed the key and value I click copy button but it doesn't work

**To Reproduce**
1. Sealed key and value pairs
2. Click on Encrypt
3. Click on Copy

**Expected behavior**
Copy button works

**Screenshots**
![image](https://user-images.githubusercontent.com/71874570/146498309-71138b25-481b-4fad-aa93-5142726a86d7.png)

**Comment by Jaydee94** [comment]
@xcloudx87 which Browser Do you use?

**Comment by xcloudx87** [comment]
@Jaydee94  Tested with chrome (Version 96.0.4664.110 (Official Build) (64-bit)) and firefox (95.0 (64-bit))

**Comment by Jaydee94** [comment]
OK strange. I cant reproduce this. I've tried this in many environments and it works for me 🤨

**Comment by xcloudx87** [comment]
Hmm I am using a domain for this, do you think it is related to?

**Comment by Jaydee94** [comment]
@xcloudx87 are you using http or https to access the application?

**Comment by xcloudx87** [comment]
@Jaydee94  It is http plain text, no https.

**Comment by Jaydee94** [comment]
Can you please try to use https?
The Clipboard API is designed to work in a secure context. We will implement a hint for the user in a further Version.

Alternatively you can try to enable Insecure origins treated as secure in chrome://flags

**Comment by xcloudx87** [comment]
@Jaydee94 I have tried with "Insecure origins treated as secure" but no luck. For HTTPS we don't have it on development environment. It is available on UAT and PROD only. 

Hmm i will copy manually to workaround this issue. Hopefully you can provide a solution for both HTTP and HTTPS.

Thanks a lot.
