### ISSUE TITLE
TypeError: Failed to fetch

### ISSUE THREAD

**Issue by BlueCog** [Jaydee94/kubeseal-webgui#140]
Hello,

First off, awesome project! 

I've deployed it succesfully on our OpenShift testenvironment (v4.9)

But when i'm trying the namespace dropdown i'm getting the following message:

```
Error while encoding sensitive data. Please contact your administrator and try again later.

Error message:
TypeError: Failed to fetch
```
`serviceaccount.create` is set to `true`. 
i've checked if the (namespace list) clusterrole & clusterrolebinding is active on the cluster 
and the service account is attached to the pod(s)

Do you have any pointers on how to troubleshoot this? I'm not seeing pointers in pod logs or namespace events...

**Comment by Jaydee94** [comment]
Hey,  @BlueCog

I will try to recreate this issue and will let you know about a solution. 
It's the first time I Heard about this Problem.

Have a great day.

**Comment by Jaydee94** [comment]
@BlueCog Maybe you Could habe a Look into the developer options of your Web Browser and Have a Look for the requests that will be send to the backend.
It Would be helpful if you Could Provide a more verbose error message.

**Comment by BlueCog** [comment]
> @BlueCog Maybe you Could have a Look into the developer options of your Web Browser and Have a Look for the requests that will be send to the backend. It Would be helpful if you Could Provide a more verbose error message.

Ah awesome, your pointer to the developer options ofd the browser brought me on the right track. I misconfigured the `api.url` setting!

Case closed :) Many thanks for the quick reply

**Comment by Jaydee94** [comment]
Great, I will close this issue. Feel free to Support the project with a github Star 😉

**Comment by Rezkmike** [comment]
Hi @BlueCog , im facing the same problem as you. So what is the solution? what should I put for ```api.url```.

**Comment by Jaydee94** [comment]
Hey @Rezkmike.

I the api.url parameter needs to be set to the public URL under which you access the application. So the hostname of your ingress.
Let me know if this solves your issue.

Best regards.

**Comment by Rezkmike** [comment]
Okay got it, thank you @Jaydee94. Now the application running well.
