### ISSUE TITLE
Missing spec.ingressClassName  in Ingress

### ISSUE THREAD

**Issue by cedvan** [Jaydee94/kubeseal-webgui#141]
**Describe the bug**
Ingress class provided by this chart only support set behavior by annotation.
So, to select ingress class, need specify an annotation `kubernetes.io/ingress.class`

But Kubernetes has deprecated this annotation
cf. https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#deprecating-the-ingress-class-annotation

This annotation is replaced by spec `ingressClassName`
cf . https://kubernetes.io/blog/2020/04/02/improvements-to-the-ingress-api-in-kubernetes-1.18/#specifying-the-class-of-an-ingress

**Expected behavior**
- Add `spec.ingressClassName` in template `ingress.yaml`
- Add a variable `ingress.class` in `values.yaml` to set this new spec

**Comment by Jaydee94** [comment]
Hey @cedvan,
it`s fixes with the new chart version 3.1.3.

**Comment by cedvan** [comment]
Hi,

Thank you, work like a charm :smile:
