### ISSUE TITLE
Add option to support scope

### ISSUE THREAD

**Issue by cedvan** [Jaydee94/kubeseal-webgui#143]
Hi,

This tool is great, thank you !!

An idea to improve it would be to permit configure scope and allow the generation of secret cluster-wide and namespace-wide.

cf. https://github.com/bitnami-labs/sealed-secrets#scopes

**Comment by FSchumacher** [comment]
Isn't this the same as #144?

**Comment by Jaydee94** [comment]
Closed with #153
