### ISSUE TITLE
Use a Python virtual env inside the API container

### ISSUE THREAD

**Issue by FSchumacher** [Jaydee94/kubeseal-webgui#147]
**Describe the bug**
When building the API container, we get a warning about not using a virtual env together with the root account:

```
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
```

**To Reproduce**
1. Go to the checked out source
2. build the API container by typing `docker build -t api:latest -f Dockerfile.api .`
3. Search for the warning above

**Expected behavior**
No such warning should appear while building the container

**Comment by Jaydee94** [comment]
Closed with #156
