### ISSUE TITLE
4.0.0 auto fetch doesn't work because of changed directory

### ISSUE THREAD

**Issue by from-nibly** [Jaydee94/kubeseal-webgui#180]
**Describe the bug**
the fetch script moved with the new docker image to ${APP_HOME}/kubeseal-webgui/bin/kubeseal-fetch.sh

the helm chart is referencing the script at /kubeseal-webgui/bin/kubeseal-fetch.sh which doesn't exist anymore

**To Reproduce**
Deploy the helm chart 4.0.0 with `sealedSecrets.autoFetchCert: true`

**Expected behavior**
Should reference the correct script

**Logs**
Error: failed to start container "fetch-cert": Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "exec: \"/kubeseal-webgui/bin/kubeseal-fetch.sh\": stat /kubeseal-webgui/bin/kubeseal-fetch.sh: no such file or directory": unknown

**Comment by Jaydee94** [comment]
@from-nibly The permissions of the shell Script are fixed in Version. 4.0.1.

I will close this issue now.

Best regards.
