### ISSUE TITLE
"Scope" and "Upload File" Fields are missing !

### ISSUE THREAD

**Issue by iennab** [Jaydee94/kubeseal-webgui#185]
Hi,
After installation in minikube (Helm Chart) , both Fields "Scope" and "Upload File " are missing. (not like the Demo)
![grafik](https://user-images.githubusercontent.com/89975709/199725181-c5701275-1d74-4af0-ad3a-c127907b622b.png)

**Comment by Jaydee94** [comment]
Heey @iennab which Version Do you use?
It's only available with Version >= 4.0.0

**Comment by iennab** [comment]
![grafik](https://user-images.githubusercontent.com/89975709/199728545-cf3bdee5-3971-43a0-acc3-3d2619128cd9.png)

**Comment by Jaydee94** [comment]
Try to use Version 4.0.1
This is the latest version which includes your requeted Features.

**Comment by iennab** [comment]
ok thx!
