### ISSUE TITLE
kubeseal-webgui : TypeError: Failed to fetch

### ISSUE THREAD

**Issue by SoufianeEddiry** [Jaydee94/kubeseal-webgui#198]
**Describe the bug**
After installing sealed secrets and the kubeseal-webgui to manage , I got TypeError: Failed to fetch.

**To Reproduce**
1. Install à vanilla k8s cluster + Ingress Controller
2. helm repo add sealed-secrets https://bitnami-labs.github.io/sealed-secrets
3. helm install sealed-secrets-controller sealed-secrets/sealed-secrets -n kube-system.'
4. helm repo add kubesealwebgui https://jaydee94.github.io/kubeseal-webgui/
5. helm install kubeseal-gui  kubesealwebgui/kubeseal-webgui --set sealedSecrets.autoFetchCert=true --set ingress.enabled=true --set ingress.hostname=webseal.dev.local

**Expected behavior**
Managing sealedsecret via the Web GUI : webseal.dev.local

**Screenshots**
![image](https://user-images.githubusercontent.com/36312828/209986645-c5b089a4-2d06-4f00-8ef7-7117ad3a76f6.png)

**Additional context**
N/A

**Comment by Jaydee94** [comment]
Hey @SoufianeEddiry.
Can you please open a Browser console and have a look at the failed request.

If you use Google Chrome you should be able to open the console with F12.

That would ne helpful to solve this issue.

**Comment by SoufianeEddiry** [comment]
Hey @Jaydee94 ,

I added the api.url with the Helm command and its Ok now.
the other issue is that the sealed secret operator decrypts sealed secret generated by the kubeseal-webgui  with "strict" scope but cannot decrypts those with a "cluster-wide" scope ??

**Comment by Jaydee94** [comment]
@SoufianeEddiry I will try to repruduce this and answer you soon.

**Comment by SoufianeEddiry** [comment]
Thank you sir

**Comment by SoufianeEddiry** [comment]
You need to add this annotation to the generated sealedsecret file:
annotations:
        sealedsecrets.bitnami.com/cluster-wide: "true"

**Comment by Jaydee94** [comment]
@SoufianeEddiry The correct labels will be rendered with the new release 4.2.0.

I will close this issue.
