### ISSUE TITLE
run the webgui under sub-url

### ISSUE THREAD

**Issue by tommoll** [Jaydee94/kubeseal-webgui#203]
example: http://some-url/kubeseal

I couldn't figure out how to run the api under a sub-url !

In the chart/kubeseal-webgui/values.yaml I see the comment:

api:
    The value of api.url should be set to the public-accessible http endpoint (ingress url or OpenShift route).
     api.url will be generated into config.json ConfigMap of the UI. This statically served JSON file
     is used by the UI to locate the API.
  url:  http://somet-url/kubeseal

But I have no success with this configuration ... 

Question: 
Is this possible?
How dow I configure this?

**Comment by Jaydee94** [comment]
Hey @tommoll.

Could you give us some more information about your problem?

What is the error that you are seeing?
How do you access the web ui?

Usually the Helm chart deploys a ingress object into your cluster that should create a URL for you.
Usually ingress objects create a sub URL of your cluster base domain.

How is your setup with the context 'http://example.com/kubeseal'?

**Comment by tommoll** [comment]
I try to setup the webgui  under a sub-url 

example.com/kubeseal

But I could not figure out how to configure the Helm chart so it adds the "kubeseal" to my cluster base domain.
The Ingress rule always points to "/" instead of "/kubeseal" . If I change the ingress rule manually  the "config.json ConfigMap of the UI" is probably wrong and the webgui is not working.

**Comment by Jaydee94** [comment]
@tommoll did you find a solution?

**Comment by tommoll** [comment]
Hi Jan, 

I decided to change to ... 

https://kubeseal.some-domain.com instead of https://some-domain.com/kubeseal 

thanks anyway ... great tool ! 

regards 


Thomas 



Von: "Jan" ***@***.***> 
An: "Jaydee94/kubeseal-webgui" ***@***.***> 
CC: "Thomas Moll" ***@***.***>, "Mention" ***@***.***> 
Gesendet: Donnerstag, 12. Januar 2023 11:02:49 
Betreff: Re: [Jaydee94/kubeseal-webgui] run the webgui under sub-url (Issue #203) 





[ https://github.com/tommoll | @tommoll ] did you find a solution?
