### ISSUE TITLE
Container image tag `latest` does not point to newest release

### ISSUE THREAD

**Issue by UiP9AV6Y** [Jaydee94/kubeseal-webgui#214]
**Describe the bug**
The README.md lists the Docker Hub as the primary source
for the container images of this project. The newest release
(as of writing this) is `4.2.2` and has a corresponding
container image in the Docker Container Registry. The image
tagged `latest` however was pushed to the Docker Container
Registry 2 years ago. The Github Workflow responsible for
deploying images (CI/main.yml) was manually run 2 years
ago. This applies to both the *ui* and *api* image

**To Reproduce**

- Observe the available image tags [1] [2] on the Docker Hub
- Observe the Github Workflow [3] responsible for deploying
  the images

[1]: https://hub.docker.com/r/kubesealwebgui/api/tags
[2]: https://hub.docker.com/r/kubesealwebgui/ui/tags
[3]: https://github.com/Jaydee94/kubeseal-webgui/actions/workflows/main.yml

**Expected behavior**

By convention container images tagged *latest* are usually
vanity tags pointing to the most recent of releases
(usually a stable release; unstable releases are generally
tagged as *nightly*)

**Additional context**

- It appears the CI workflow for the image release
  was triggered manually
- It appears container images are deployed to the Docker
  Container Registry manually rather than via the CI workflow

**Comment by Jaydee94** [comment]
Hey, @UiP9AV6Y I will have a look at this. Thanks for your bug report.
