### ISSUE TITLE
Typo in chart service selector spec

### ISSUE THREAD

**Issue by UiP9AV6Y** [Jaydee94/kubeseal-webgui#23]
there is no workload with the label [pp](https://github.com/Jaydee94/kubeseal-webgui/blob/023b5c431338e57b75fcf2d5667a8502f43b3796/chart/kubeseal-webgui/templates/service.yaml#L9), so the service is pointing into the void.

**Comment by Jaydee94** [comment]
@UiP9AV6Y thanks for youre Bug report, we will fix this ASAP.
