### ISSUE TITLE
Vulnerabilities detected in latest release (4.2.2)

### ISSUE THREAD

**Issue by fletch3555** [Jaydee94/kubeseal-webgui#234]
**Describe the bug**
Latest release of the kubesealwebgui/ui image has vulnerabilities related to curl, likely coming from the base image.

**To Reproduce**
1. Run trivy or a similar image vulnerability scanner tool
2. Review results
3. See 2x Critical (both curl) and 21x High vulnerabilities (curl/libcurl, libssl3, ncurses, etc.  All seem to be from OS/base-image)

**Expected behavior**
There should be no critical vulnerabilities detected

**Screenshots**
![image](https://github.com/Jaydee94/kubeseal-webgui/assets/1387843/168b581b-7d2f-4e3f-867e-00f54235efd5)

(Image from local Harbor instance, so unable to share direct link)

**Additional context**
Simply rebuilding the image (and releasing a new version) should be enough to resolve a vast majority, if not all, of these issues.

If there's anything I can do to help, please let me know.

**Comment by Jaydee94** [comment]
Hi @fletch3555 i will release a newer version of the image soon with an updates base image and updated dependencies.
Best regards.

**Comment by fletch3555** [comment]
Thanks for the super-fast reply!

**Comment by Jaydee94** [comment]
@fletch3555 I've just released a newer version of kubeseal-webgui and scanned it with trivy. There are just 2-3 CVEs left but they are in the base images that i use...
I will mark this issue als solved.

**Comment by fletch3555** [comment]
Perfect.  Just showing a single "High" vulnerability for me now, which is acceptable for our needs.  Thanks!
