### ISSUE TITLE
Helm chart: clusterRole need verb get

### ISSUE THREAD

**Issue by sandrospadaro** [Jaydee94/kubeseal-webgui#240]
**Describe the bug**  
The application fails to operate correctly due to insufficient permissions within the OpenShift cluster. Specifically, it requires the `list` and `get` verbs to be enabled for certain resources, but these permissions can not to be set. Without these permissions, the application is unable to query the cluster for necessary information, leading to operational failures.

**To Reproduce**  
1. Deploy the application on OpenShift version 4.12.27 with Kubernetes version 1.25.
2. Attempt to initiate the application's primary functionality.
3. The application fails to retrive namespaces.
4. The error log indicates a lack of permissions.

**Expected behavior**  
The application should seamlessly list and retrieve the namespaces from the OpenShift cluster without encountering permission errors. Proper setup should include all necessary permissions for the application's service account, ensuring it can execute `list` and `get` operations as intended.

**Screenshots**  
If applicable, add screenshots to help explain your problem. (N/A)

**Additional context**  
The issue was encountered in an OpenShift cluster, version 4.12.27, running Kubernetes version 1.25. 

**Proposd solution**
Edit `chart/kubeseal-webgui/templates/clusterrole.yaml` file and replace `verbs: ["list"]` with `verbs: ["list", "get"]` [here](https://github.com/Jaydee94/kubeseal-webgui/blob/68eb83a0eac73aaedd1b58001588f01bd304a25d/chart/kubeseal-webgui/templates/clusterrole.yaml#L15).

**Comment by Jaydee94** [comment]
Hey @sandrospadaro thanks for your bug report.
I'm a bit confused. We also run the application in our OpenShift clusters with the helm chart provided in this repository

Can you specify the error message you receive? Maybe the logs of the API server?

Beside this I will try to reproduce this issue.

Best regards.

**Comment by sandrospadaro** [comment]
Hi jaydee94
You are right. Please ignore this issue. I apologize for the error.

**Comment by Jaydee94** [comment]
@sandrospadaro No problem :)

I will mark this issue as resolved.
