### ISSUE TITLE
Can we get a new release?

### ISSUE THREAD

**Issue by fletch3555** [Jaydee94/kubeseal-webgui#246]
Apologies for bypassing the issue template, but this isn't a bug report per-se.

There hasn't been any activity on this project in 8 months now.  New vulnerabilities have been detected (by trivy) in the latest released version (4.2.5).  These are mostly OS-level packages (libexpat, krb5).  Since you use `debian:latest` as the base image, I think simply building a new image would pull in an updated base image and resolve them.  If there are updated versions of kubeseal or other changes to be made, that would be an added bonus.

Could a maintainer please release an update version to resolve these?

Thanks!

**Comment by Jaydee94** [comment]
Hi @fletch3555 ,

Thanks for your request to update the images. 
We hadn't paid much attention to the project recently. I will update the container images soon and make a patch release.

Also there will be more activity in october. Hacktoberfest is coming 😊

**Comment by fletch3555** [comment]
Thank you!

**Comment by Jaydee94** [comment]
Update images are released :)
