### ISSUE TITLE
[Improvement] Don't use the Flask development server in production

### ISSUE THREAD

**Issue by pydo** [Jaydee94/kubeseal-webgui#34]
Hi,

First off I think this project is really cool. I was thinking of building custom tooling on top of `kubeseal` until I found this app :slightly_smiling_face: .

I don't think it's a great idea to run the Flask development server in production environments, see https://github.com/Jaydee94/kubeseal-webgui/blob/master/Dockerfile.api#L24 .

Some alternatives:
- https://uwsgi-docs.readthedocs.io/en/latest/WSGIquickstart.html?highlight=flask#deploying-flask
- https://flask.palletsprojects.com/en/1.1.x/deploying/wsgi-standalone/#gunicorn

I could handle this task myself if you're interested.

**Comment by Jaydee94** [comment]
Hi,
Thanks for your Feedback. Feel free to do a PR :)

Best Regards 
Jan
