### ISSUE TITLE
[Improvement] Optionally auto-detect public-cert from sealed secrets controller

### ISSUE THREAD

**Issue by Jaydee94** [Jaydee94/kubeseal-webgui#40]
Currently it is required to manually configure the public certificate to seal secrets. It should be possible to optionally retrieve the public cert of the sealed secrets controller by providing the namespace and the controller name.

**Comment by bork91** [comment]
Another option could be to give the URL to the public certificate. So the certificate is fetched on encrypt.

**Comment by Jaydee94** [comment]
@bork91 Thanks for your suggestion. Would you like to implement it?
